# luci-theme-material2
# 		Copyright 2018 Stanley Ang.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Material Theme Based on Bootstrap
LUCI_DEPENDS:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
